# Generated by Django 3.2 on 2021-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='bio',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owner',
            name='date_created',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='owner',
            name='profile_picture',
            field=models.ImageField(default='accounts/user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='owner',
            name='user_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
