# Generated by Django 3.2 on 2021-04-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210413_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_created',
            field=models.DateTimeField(default=True),
        ),
    ]
